WITH CTE AS (
Select

TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) as DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) as HOUR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTED_AT)) as DAYNAME_STARTED_AT,
CASE WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
Then 'WEEKEND'
ELSE 'BUSINESSDAY' END AS DAY_TYPE,
MONTH(TO_TIMESTAMP(STARTED_AT)) as MONTH_STARTED_AT,

CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2)
Then 'WINTER'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (3,4,5)
Then 'SPRING'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8)
Then 'SUMMER'
ELSE 'AUTUMN' END AS STATION_OF_YEAR

from 
{{ source('demo', 'bike') }}
where 
STARTED_AT!='started_at'
)

Select *
from CTE